#on: [pull_request]
#
#jobs:
#  main:
#    runs-on: ubuntu-latest
#    name: Refactoring Detection
#    steps:
#      - name: Git Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: RefDiff
#        env:
#          LANGUAGE: Java
#          REV_BEFORE: ${{ github.event.pull_request.base.sha }}
#          REV_AFTER: ${{ github.event.pull_request.head.sha }}
#        uses: rodrigo-brito/refactoring-aware-diff@action

name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
